### PR TITLE
Implement addUser and activate with external email

### PR DESCRIPTION
**Pull request by chuan9**

### CODE REVIEW

**Comment by chuan9** [comment]
@wagmarcel @jelyoussefi PTAL, thanks

**Comment by wagmarcel** [comment]
Please remove the PW - for the time being we need to configure it manually

**Comment by chuan9** [comment]
@wagmarcel @jelyoussefi Already remove PW and we can config imap in test-config.json. PTAL, thanks

**Comment by wagmarcel** [comment]
as discussed with @jelyoussefi  I am closing and waiting for the new patch

**Pull request closed without merging**
