### PR TITLE
Added refresh token subtests

### PR DESCRIPTION
**Pull request by oguzcankirmemis**
Signed-off-by: Oguzcan Kirmemis <oguzcan.kirmemis@gmail.com>

### CODE REVIEW

**Comment by oguzcankirmemis** [comment]
@wagmarcel ready to merge.

**Comment by wagmarcel** [comment]
@oguzcankirmemis: Looks good.
When the refresh token is revoked, shouldn't we also check that trying to use it will fail after that?

**Comment by oguzcankirmemis** [comment]
@wagmarcel: It is also checked in the test "revokeRefreshToken", if it can be used an error is thrown. Should I make this a seperate test after revoking instead of packing them together?

**Comment by wagmarcel** [comment]
@oguzcankirmemis: ah ok, overlooked that. Then it is fine. will merge it.

**Pull request merged**
