### PR TITLE
Keycloak: added realm migration script, closes #478

### LINKED ISSUE #478: Keycloak migration container for each release

### PR DESCRIPTION
**Pull request by oguzcankirmemis**
Signed-off-by: Oguzcan Kirmemis <oguzcan.kirmemis@gmail.com>

### CODE REVIEW

**Comment by wagmarcel** [comment]
@oguzcankirmemis this container is not created automatically right? Would't it be better if there is another container like "keycloak-migration" which is always created but only used if I configure it in the keycloak deyployment?

**Comment by oguzcankirmemis** [comment]
@wagmarcel do you mean that we always have a migration container, which contains the current realm configuration? This makes sense. In the current way you need to manually run the migration script inside the container, once the container is running. However, we already have startup script in our keycloak images, so this startup script can check whether the container contains a migration script and runs it. Nonetheless, I am reluctant to seperate the images, because the migration container is essentially an oisp/keycloak container that has a migration script as bonus.

Another idea would be to merge both containers, and control the behavior of the container with an environment variable, like "$FORCE_MIGRATION=true".

The final problem for the automatization would be the difference between realm files in a migration container and a standard container. The realm files of the migration container should not contain the service accounts (frontend uses one of them for administrative purposes). I guess, the approach would be to separate the users from the realm config, and put it back in runtime if necessary. 

Let me know what you think.

**Comment by wagmarcel** [comment]
> Another idea would be to merge both containers, and control the behavior of the container with an environment variable, like "$FORCE_MIGRATION=true".
> 
Sounds good, let's try it.

**Review by wagmarcel — DISMISSED** [review]
see comments on environment variable
Please add this feature.

**Comment by oguzcankirmemis** [comment]
Ready for re-review.

**Review by wagmarcel — APPROVED** [review]

**Pull request merged**
