### PR TITLE
Changed default backend to Cassandra/KairosDB

### PR DESCRIPTION
**Pull request by wagmarcel**
* New KairosDB Container replacing OpenTSDB
* Cassandra cluster is managed by operator and replacing HBASE/HDFS
* Removed HBase/Hdfs traces in config as much as possible (not completely wiped due to formal depenencies e.g. of rule-engine)

Signed-off-by: Marcel Wagner <wagmarcel@web.de>

### CODE REVIEW

**Comment by wagmarcel** [comment]
@oguzcankirmemis: This Pull request is replacing openTSDB datasource with Kairos. As you can see, all tests are successful, but only a few Grafan tests are failing. Can you please take a look and check what needs to be done to make Grafana tests pass?

**Comment by oguzcankirmemis** [comment]
@wagmarcel : To make it work with Grafana, we need two more things:

- Adjusting the configuration file kairosdb.yaml (current one contains some openTSDB specific options like tsdbVersion)
- Adding Kairos proxy to the frontend for security (very similar to the openTSDB one)

Should be easy, I will notify you when it is done.

**Comment by oguzcankirmemis** [comment]
@wagmarcel currently testing the grafana update, but I can't manage to send data to frontend. I get the following error: 
`error: Error when forwarding observation to Kafka: {"message":"Broker not available (loadMetadataForTopics)"}`

Did I do something wrong during the migration to KairosDB?
I use newly built fresh images for frontend/backend/kairos/grafana.

**Comment by wagmarcel** [comment]
@oguzcankirmemis that is strange. When you look at the e2e test result: All tests passed except grafana. So I assume that in principle it shoud work. I will test it locally to be sure.

**Comment by wagmarcel** [comment]
@oguzcankirmemis I just checked it on my side. It has the same result like the E2E on Circleci: Only grafana tests are failing, the rest works.  
I have a suspect: Did you restart the cluster? Might be that the Kafka/Zookeeper operators were not installed properly? You can check whether you have for instance at least two pods in the  kafka namespace: 1 pod for operator and 1 pod the actual kafka service.

**Comment by oguzcankirmemis** [comment]
After merging the [PR](https://github.com/Open-IoT-Service-Platform/oisp-frontend/pull/187) at the frontend, this can be merged by applying the changes in #256 (last commit). I don't know what is the best practice here? Should I rebase mine and merge the into single commit or do you want to rebase it yourself? In any case I should point out that I had to change the code in the tests simply due to the fact that the APIs & plugins of OpenTSDB and KairosDB do not match. I think the system overall system is now more lightweight and faster - especially tests -, so I thank you for that.

**Pull request closed without merging**
