### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by nevets963**
Fix broken submodule to oisp-agent

### CODE REVIEW

**Comment by jelyoussefi** [comment]
Hi Steven
I still have the issue

**Comment by wagmarcel** [comment]
I can build succesfully, and the git submodule update works now.
But test does not run through successful on my side:
Possibly unhandled SequelizeDatabaseError: schema "dashboard" does not exist

**Comment by nevets963** [comment]
Is this when running ‘make test’ straight after a build?

**Comment by wagmarcel** [comment]
yes, when I do make test from scratch

**Pull request merged**
