### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nevets963**

### CODE REVIEW

**Comment by nevets963** [comment]
@chuan9 @Cloud-Chen I already implemented something to use an env. variable for the docker compose project name. Could you guys look at this?

**Comment by Cloud-Chen** [comment]
Hi Steven,
                So user can update the script for the name? Will this impact the global setting of  compose_project_name? Thanks.
Best Regards
                Cloud

**Comment by nevets963** [comment]
@Cloud-Chen The user can set the project name using the COMPOSE_PROJECT_NAME environment variable

**Comment by arkocal** [comment]
Do not merge! Seems like some more recent updates are incompatible with this PR, I am currently working on it.

**Comment by arkocal** [comment]
I have merged the changes in my develop branch and made further changes. See #45

**Pull request closed without merging**
